# Generated by Django 3.1.7 on 2021-03-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributions',
            new_name='Contribution',
        ),
    ]
