# Generated by Django 3.1.7 on 2021-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='max_visit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='min_away',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='no_procrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='show_dead',
            field=models.BooleanField(default=False),
        ),
    ]
