# Generated by Django 3.1.7 on 2021-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
