# Generated by Django 3.1.7 on 2021-03-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0002_auto_20210322_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='content',
        ),
        migrations.AddField(
            model_name='contribution',
            name='text',
            field=models.CharField(default='Carles', max_length=200),
        ),
        migrations.AddField(
            model_name='contribution',
            name='title',
            field=models.CharField(default='Oriol', max_length=200),
        ),
        migrations.AddField(
            model_name='contribution',
            name='url',
            field=models.CharField(default='Oriol', max_length=200),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='HackerNews.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
