# Generated by Django 3.1.7 on 2021-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0002_auto_20210421_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
    ]
