# Generated by Django 3.1.7 on 2021-04-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0003_comment_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='father',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HackerNews.comment'),
        ),
    ]
