# Generated by Django 3.1.7 on 2021-04-11 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0004_auto_20210411_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HackerNews.comment'),
        ),
    ]
