# Generated by Django 3.1.7 on 2021-04-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HackerNews', '0007_auto_20210411_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HackerNews.contribution'),
        ),
    ]
